[[build]]
  command = "npm run build"
  publish = "client/build"
  base ="/"

[[build]]
  command = "npm run build"
  publish = "api/build"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
